### ISSUE TITLE
Wrong output dataframe?

### ISSUE THREAD

**Issue by antoniocali** [pola-rs/polars-book#398] opened 2023-09-07 16:16 UTC
I'm looking at this part of user guide generated by this specific line

https://github.com/pola-rs/polars-book/blob/1e0beafbda8cee0aecc45871a50ee16bb394a6ca/docs/src/python/user-guide/expressions/column-selections.py#L65

What users guide says is

```python
out = df.select(cs.by_name("rn") | ~cs.numeric())
print(out)
```

gives as output

```python
shape: (3, 4)
┌────────┬────────────┬────────────┬─────────────────────┐
│ place  ┆ date       ┆ has_people ┆ logged_at           │
│ ---    ┆ ---        ┆ ---        ┆ ---                 │
│ str    ┆ date       ┆ bool       ┆ datetime[μs]        │
╞════════╪════════════╪════════════╪═════════════════════╡
│ Mars   ┆ 2022-01-01 ┆ false      ┆ 2022-12-01 00:00:00 │
│ Earth  ┆ 2022-01-02 ┆ true       ┆ 2022-12-01 00:00:01 │
│ Saturn ┆ 2022-01-03 ┆ false      ┆ 2022-12-01 00:00:02 │
└────────┴────────────┴────────────┴─────────────────────┘
```

But I cannot understand why in the output selection the column `rn` is missing

**Comment by antoniocali** [comment] 2023-09-07 16:17
To clarify,
I've tested locally and output is indeed as shown in doc guide, even so, I don't understand why.
Shouldnt `rn` column appear?

**Comment by avimallu** [comment] 2023-09-07 20:48
I'm not sure - it was working as intended when I wrote it, so something must have changed. Can you open this as an issue in the main Polars repo and link to this issue?

**Comment by antoniocali** [comment] 2023-09-08 07:18
Sorry but link do not directs me unfortunately to the correct line.

And not sure what it is missing from the test output.

Should I still open this as an issue on polars?

**Comment by antoniocali** [comment] 2023-09-12 08:23
It was raised the issue on polars, and it was fixed. I suppose when new release will be out, this would automatically fix also the documentation.
Should we probably close, right @avimallu ?

**Comment by avimallu** [comment] 2023-09-12 14:07
Yeah, closing it is a good idea. It won't be reflected in the user guide until another commit is merged though, since the builds are refreshed only then AFAIK.

**Comment by stinodego** [comment] 2023-09-12 14:24
@avimallu The user guide is refreshed when a new commit is merged here.

The user guide is in the process of being moved into the main repo - then it will be updated with each Python release. Will probably happen later this week.

**Comment by stinodego** [comment] 2023-09-14 09:27
This should be resolved once the new Python release is out. If not, please open a new issue in the main repo.

**Closed by stinodego** 2023-09-14 09:27 UTC
